spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tduck?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  mail:
    host: smtp.163.com
    username: test@163.com  # 邮箱账号
    password: DSXFPX24XOBURMDY #邮箱授权码

logging:
  level:
    com.tduck.cloud: debug
  config: classpath:logback-spring.xml

#  请求日志是否打印
platform:
  qq:
    oauth:
      appId:
      secret:
  oss:
    ossType: 3 # 本地存储
    endpoint:
    accessKeyId:
    accessKeySecret:
    bucketName:
    domain:   #提供访问的域名
    upload-folder:  #文件存放的位置
    access-path-pattern: /profile/**  # 文件访问路径前缀 这里更改domain也需要更改
  sms:
    type: 1  # 短信平台类型
    secretId: Ga2AIryi8174KXz  #短信秘钥
    secretKey: uHSpKfjtadadaezjwtN6B0dvbelv #短信秘钥
    appId:
    sign: tduck                  #短信签名
    validateCodeTemplateId: SMS_219865038 #验证码模板
    retrievePwdValidateCodeTemplateId: SMS_219865039  # 找回密码模板
  front:
    baseUrl: https://demo.tduckapp.com/
    resetPwdUrl: https://demo.tduckapp.com/forget/password?code={}&email={}
    updateEmailUrl: https://demo.tduckapp.com/account/forget/validate?type=updateEmail&code={}&email={}

wx:
  mp:
    configs:
      - appId:   #公众号appId
        secret: #公众号秘钥
        token: dHClTzEAcayUX0Jyy9TwBp89QrdWvvZZ
        aesKey: 3aNsbtc8wdx92M14YszvQSU4zksx9M1Gl8k655vYOLB

